tomerfiliba/plumbum

- plumbum/commands/base.py
- plumbum/commands/processes.py
- plumbum/lib.py
- plumbum/machines/local.py
- plumbum/machines/paramiko_machine.py
- tests/test_local.py
- tests/test_remote.py
- Support and fix iter_lines on all machine types. Implement on the popen object instead of the command objects
- Closes #154
> Misc Fixes

- plumbum/machines/remote.py
You may not want this fix—read #178 and decide whether the imperfect but faster solution suggested by pigay in #162 is a better fallback for non-GNU systems than this one. But you definitely want **something**, because as it stands you can't access the remote environment at all on OS X, FreeBSD, etc.
- Since `env -0` is a GNU extension, we need some fallback for OS X, etc.
- Parsing `env` into `name=value` lines (skipping the ones without `=`),
then calling `printenv $name` on each name (skipping the ones that
don't exist) should work portably, although obviously more slowly.
> Fall back to `printenv` per variable if no `env -0` (#178).

- plumbum/machines/remote.py
This is for #180. I put my comments in that issue instead of this PR: https://github.com/tomerfiliba/plumbum/issues/180#issuecomment-118069755.
> Add Darwin/OSX variant of stat format to support operations on remote OSX servers

- plumbum/machines/session.py
- tests/test_remote.py
sshpass does error reporting with its returncode:
1 Invalid command line argument
2 Conflicting arguments given
3 General runtime error
4 Unrecognized response from ssh (parse error)
5 Invalid/incorrect password
6 Host public key is unknown. sshpass exits without confirming the new key.
This patch tries to check the return code on error cases and reports an
appropriate error, so in the case of an invalid login or missing host
public key, we get a useful error message instead of a generic
SSHCommsError.
> Check the returncode of sshpass when reporting errors

- plumbum/cli/termsize.py
> 	modified:   plumbum/cli/termsize.py

- plumbum/machines/paramiko_machine.py
Added for Kerberos authentication. Please let me know if anything is incorrect, since this is my first pull request.
> Adding support for GSS-API (Paramiko 1.15 and above needed)

- .gitignore
- plumbum/__init__.py
- plumbum/cli/application.py
- plumbum/cli/config.py
- plumbum/cli/i18n.py
- plumbum/cli/progress.py
- plumbum/cli/switches.py
- plumbum/cli/termsize.py
- plumbum/colorlib/_ipython_ext.py
- plumbum/colorlib/styles.py
- plumbum/commands/base.py
- plumbum/commands/modifiers.py
- plumbum/commands/processes.py
- plumbum/lib.py
- plumbum/machines/local.py
- plumbum/path/local.py
- plumbum/path/remote.py
- tests/conftest.py
- tests/test_3_cli.py
- tests/test_validate.py
This PR improved the interaction with MyPy, and fixes #342.
> WIP: Better interaction with MyPy

- plumbum/lib.py
- plumbum/machines/remote.py
As described in my comment, I just moved the code to `BaseRemoteMachine` and called those methods from `RemoteEnv` :)
> Fix #293: AttributeError: 'SshMachine' object has no attribute 'env'

- .ci/travis.sh
- .travis.yml
- dev-requirements.txt
Working on a fix for Python 2 macOS and Python 2.6 on Travis.
> WIP: Attempt to fix travis macOS and py26

- plumbum/cli/i18n.py
Should remove the hard requirement that setup tools be installed. Doesn't fix a possible speed issue with translations.
> Adding non-setuptools check

- .appveyor.yml
- tests/test_local.py
> Appveyor fixes

- .travis.yml
- plumbum/cli/progress.py
- tests/test_terminal.py
> Fix div by 0 error

- plumbum/machines/paramiko_machine.py
> ParamikoMachine: respect ProxyCommand from SSH config.

- docs/local_commands.rst
Pretty self-explanatory; I noticed that some more links to the API docs could be helpful while answering #425.
> Some more links in docs on local commands

- tests/test_local.py
This hopefully will no longer fail.
> Dropping xfail as mentioned in #395

- .travis.yml
Adding deploy to PyPI to Travis.
> Adding deploy

- plumbum/path/base.py
[Discussion](https://github.com/tomerfiliba/plumbum/issues/445#issuecomment-542421228) at #445
> truer docstrings for read/write, regarding input/output types

- plumbum/commands/base.py
- plumbum/commands/modifiers.py
(seems like some previous refactoring was left incomplete...)
> bug fixes around 'nohup'

- docs/index.rst
- docs/typed_env.rst
- plumbum/typed_env.py
@AndydeCleyre - maybe you can comment on these docs?
> Typed env docs

- .ci/travis.sh
- .travis.yml
As seen recently, for example, in #497.
> Attempting to fix broken Python 2.6 & PyPy2

- plumbum/path/remote.py
> Fix remote stat OSError construction

- setup.py
Will help when we drop 2.6 in the next non-patch release.
> Add Python requires spec

- .ci/travis.sh
- .travis.yml
> Install libssl1.1 in travis.sh

- tests/test_remote.py
tests `RemotePath.copy` for the following scenarios:
* copying a simple file from `file_a` to `copy_of_a` succeeds
* copying file `file_a` into a directory `a_dir/copy_of_a` succeeds
* copying a directory `a_dir` over an existing directory path with
`override=False` fails
* copying a directory `a_dir` over an existing directory path with
`override=True` succeeds
> adds test for RemotePath.copy method

- .github/workflows/ci.yml
Hoping to see the problem in #513 , also touching up a couple of things.
> ci: pipx and allow workflow_dispatch

- docs/index.rst
> docs: mention setuptools_scm, fix version list

- .github/workflows/ci.yml
Might not be critical, but probably a good idea at least.
> ci: include service for final codecov step

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- plumbum/machines/ssh_machine.py
- setup.cfg
- tests/test_putty.py
- tests/test_remote.py
Fix for #562, plus testing improvements and skips. More coverage (full 3.10, PyPy 3.8).
> fix: issue in recent PR plus more testing

- pyproject.toml
> tests: fix config options

- CHANGELOG.rst
- plumbum/colorlib/styles.py
- plumbum/machines/paramiko_machine.py
- plumbum/path/base.py
- tests/test_remote.py
See https://no-color.org. Quite a few tools support FORCE_COLOR now too, like nox and pytest.
> feat: support forcing color/nocolor

- docs/cli.rst
- plumbum/cli/config.py
- plumbum/lib.py
- plumbum/machines/paramiko_machine.py
- plumbum/machines/remote.py
- plumbum/machines/ssh_machine.py
- plumbum/path/base.py
- plumbum/path/local.py
- plumbum/path/remote.py
Cleans up issues with mypy not handling decorators on properties.
> chore: remove setdoc (not needed in Py3)

- docs/cli.rst
- docs/colorlib.rst
In the documentation use f-strings in the examples.
> Use f-strings instead format.

- .github/matchers/pylint.json
- .github/workflows/ci.yml
- .pre-commit-config.yaml
- plumbum/commands/base.py
- plumbum/commands/daemons.py
- plumbum/commands/processes.py
- plumbum/machines/local.py
- plumbum/machines/paramiko_machine.py
- plumbum/machines/remote.py
- pyproject.toml
Also cleaning up the double assignment and `_INFINITY` constant from  #582 using `math.inf` from Python 3.5+.
- ci: nicer pylint output
- style: use math.inf
> ci: nicer pylint annotations

- .pre-commit-config.yaml
- plumbum/cli/application.py
- plumbum/commands/base.py
- plumbum/machines/paramiko_machine.py
- plumbum/machines/remote.py
See https://github.com/psf/black/issues/2964 for details.
> style: bump black

- .pre-commit-config.yaml
- CHANGELOG.rst
- plumbum/colorlib/factories.py
- plumbum/commands/processes.py
- plumbum/machines/remote.py
- plumbum/path/utils.py
- pyproject.toml
> docs: update changelog

- .pre-commit-config.yaml
- noxfile.py
- plumbum/cli/image.py
- plumbum/cli/progress.py
- plumbum/colorlib/__init__.py
- plumbum/colorlib/styles.py
- plumbum/commands/processes.py
- plumbum/fs/atomic.py
- plumbum/path/base.py
- plumbum/path/local.py
- plumbum/path/remote.py
- plumbum/typed_env.py
- setup.cfg
- tests/test_validate.py
- fix: ABC was applied to the wrong class
- chore: update style and fix a few issues
> fix: abc & a few style issues

- plumbum/cli/application.py
- plumbum/cli/config.py
- plumbum/cli/switches.py
- plumbum/cli/terminal.py
- plumbum/cli/termsize.py
- plumbum/colorlib/factories.py
- plumbum/colorlib/styles.py
- plumbum/commands/base.py
- plumbum/commands/daemons.py
- plumbum/commands/processes.py
- plumbum/fs/atomic.py
- plumbum/machines/local.py
- plumbum/machines/paramiko_machine.py
- plumbum/machines/remote.py
- plumbum/machines/session.py
- plumbum/path/base.py
> chore: minor cleanups from reverb

- .github/workflows/ci.yml
- noxfile.py
- tests/test_local.py
Adding 3.11 testing before a release.
> ci: add testing for 3.11

- .pre-commit-config.yaml
- plumbum/cli/application.py
- plumbum/cli/image.py
- plumbum/cli/progress.py
- plumbum/cli/switches.py
- plumbum/cli/terminal.py
- plumbum/colorlib/styles.py
- plumbum/commands/modifiers.py
- plumbum/commands/processes.py
- plumbum/machines/paramiko_machine.py
- plumbum/machines/remote.py
- plumbum/machines/ssh_machine.py
- pyproject.toml
- tests/conftest.py
- tests/test_cli.py
- tests/test_remote.py
Updating, newer Ruff found one mistake in tests.
> chore: update pre-commit hooks

- .github/workflows/ci.yml
- noxfile.py
- pyproject.toml
> ci: add 3.12 beta testing

- .pre-commit-config.yaml
- conda.recipe/README.mkd
- experiments/parallel.py
- noxfile.py
- plumbum/__init__.py
- plumbum/_testtools.py
- plumbum/commands/processes.py
- plumbum/machines/local.py
- plumbum/path/base.py
- plumbum/path/local.py
- pyproject.toml
- tests/test_local.py
- tests/test_remote.py
Probably dropping 3.6 very soon, as it's well past EoL. Not _quite_ yet, though. (3.7 is also past EoL)
> chore: bump pre-commit

- .github/workflows/ci.yml
> ci: bump CI

- noxfile.py
- pyproject.toml
- tests/test_local.py
Some minor touchups.
- chore: add a couple of pytest options
- chore: tracemalloc for nox
> chore: config

- .pre-commit-config.yaml
- MANIFEST.in
- noxfile.py
- pyproject.toml
- setup.cfg
> chore: clean up codespell

- .github/workflows/ci.yml
PyPy is still slow. Trying this.
> ci: adjust uv cache

- docs/_news.rst
your site looked weird having a wrong date order. found out it was a typo.
> fixed wrong date

- .github/workflows/ci.yml
- .readthedocs.yml
- plumbum/cli/i18n.py
- plumbum/cli/switches.py
- plumbum/path/local.py
- pyproject.toml
- tests/test_remote.py
I expect issues with Windows until pywin32 is ready.
> feat: add Python π, drop Python 3.8

- plumbum/path/local.py
Followup to #705, based on comment in https://github.com/python/cpython/issues/125974.
> chore: simpler urljoin
