plumbum/machines/remote.py

See #175. Briefly, `mktemp -d` with no other parameters is only legal on the GNU version of `mktemp`, not the BSD version; explicitly passing the GNU version's default works on both.

Add template to `mktemp` to fix #175

---

plumbum/cli/switches.py

https://github.com/tomerfiliba/plumbum/issues/183

plumbum.cli.Flag shouldn't print the default on execution of --help

---

plumbum/machines/paramiko_machine.py

Paramiko supports the ssh keepalive mechanism. This patch exposes the mechanism to the ParamikoMachine. I'm not sure if this is the ideal way to implement it (any suggestions welcome), but I wrote this because I need to enable keepalive and can't reliably set it server side for every server I talk to.

Add support for paramiko set_keepalive

---

plumbum/machines/remote.py

This PR just fixes a little mismatch in BaseRemoteMachine._path_link between the arguments in the format string and the format tuple. I changed the `"-s"`in the format string to a `%s` that should get replaced by `"-s" if symlink else ""` at run time, which appears to have been the original intent.

Fix mismatch between format string and format tuple in remote._path_link

---

docs/local_machine.rst
examples/.gitignore
examples/make_figures.py
examples/testfigure.tex
plumbum/path/base.py
plumbum/path/local.py
plumbum/path/remote.py
tests/test_local.py
tests/test_remote.py

The suffix, suffixes properties and` with_name`, `with_suffix` methods were added
(names chosen to be similar to other packages, like the builtin `pathlib`). One
difference vs. pathlib is an optional parameter for the `with_suffix` method that
allows simple manipulation of extended suffixes, like `.tar.gz`.
These additions are useful for working with multiple files of the same name,
such as when compiling programs or documents, and for packing/changing
compressed files.
Documentation, local and remote (and base class) support, unittests, and an
example were added.
As a quick example, here is .tar.gz -> .zip conversion, adopted from the bash script at http://stackoverflow.com/questions/6301885/convert-tar-gz-to-zip :
```python
from plumbum import local
from plumbum.cmd import tar, zip, …
```

Adding suffix methods and properties

---

plumbum/path/local.py

It appears that in Python 2.x on Windows `os.unlink(path)` can't remove symbolic links to folders, and it's necessary to use `os.rmdir(path)` instead. In Python 3.x, this appears to have been fixed along with generally adding support for `os.symlink` in Windows.
This patch adds special casing to `LocalPath.unlink` to enable deleting symbolic links to folders in Windows. I chose to duplicate the `hasattr(os, "symlink")` feature-detect from the `LocalPath.symlink` method, as that will still use `os.unlink` all the time if `os.symlink` is available (Python 3.x, or Python 2.x on Unix-y systems). Additionally, if `not self.isdir()`, such as for files or for symbolic links to files, we still call `os.unlink` as before.
A side-effect of this change is that for Python 2.x on Windows, calling …

Enable unlinking of symbolic links to folders in Windows

---

docs/local_commands.rst
plumbum/__init__.py
plumbum/commands/__init__.py
plumbum/commands/modifiers.py
tests/test_local.py

I was writing a little tutorial for plumbum and converting one of my more complex bash scripts to plumbum, and I noticed one common use that `subprocess.call` does well that plumbum works a little harder for. It was in checking and working with return codes. While the exception method is excellent, if you are working with, for example, git, and you want to toggle behavior based on the return code of a command (like `git rev-list HEAD..origin`), then you have to use `.run(retcode=None)[0]` or try/except blocks (which then require accessing the stdin/stderr differently in the except block).
I added two modifiers alongside FG and BG, namely TF and RETCODE, that make working with return codes easy and natural in plumbum. They work a lot like BG, for example:
```python
>>> git['rev-list', …
```

Two more modifiers for return codes

---

plumbum/cli/application.py

The library evaluates the sys.argv at the [wrong time](http://docs.python-guide.org/en/latest/writing/gotchas/), since it is a list being given as a default argument. Compare to argparse in IPython:
%%writefile test_argparse.py
import argparse
def main():
parser = argparse.ArgumentParser(description='Echo a command in color.')
parser.add_argument('-c','--color', type=str,
help='Color to print')
parser.add_argument('echo',
help='The item to print in color')
args = parser.parse_args()
print('I should print', args.echo, 'in', args.color, "- but I'm lazy.")
if __name__ == '__main__':
main()
Overwriting test_argparse.py
Then, run it:
%run test_argparse.py -c red item
I should print item in red - but I'm lazy.
%run test_argparse.py -c green item
I should print item in green - but I'm lazy.
Now, …

BUGFIX: Early binding to mutable list

---

plumbum/machines/paramiko_machine.py

Not sure if this is actually interesting since it does represent a bit of a regression in support, but this adds a sftp backed `_path_stat`. This, however, gives up `st_ino`, `st_dev`, `st_nlink` and `st_ctime`.
The real problem is that paramiko and openssh only implement sftp v3. I'm not so sure how widely supported v4 - v6 are, but those specs expand what stat returns. v4, for example, adds at least `st_ctime`.

Implement a pure sftp backed _path_stat

---

plumbum/commands/modifiers.py

Works and produces same results on python3.4 and python2.7 on my machine.
Closes #185

Fixing TEE modifier for python3.

---

plumbum/lib.py
plumbum/machines/local.py
tests/test_local.py

This patch makes the `local.cwd` the current working directory, not just the current working directory when Plumbum loaded, so code like this now works:
```python
assert local.cwd == os.getcwd()
os.chdir('../plumbum')
assert local.cwd == os.getcwd()
os.chdir('../tests')
assert local.cwd == os.getcwd()
```
The `cwd` is now a descriptor in the local machine (and works from class or object access). Added a test similar to the lines above to verify that it works.
(Example of use case: This is a common problem when working with Plumbum in IPython and trying to use `local.cwd` to find files after changing the directory with `cd`.)

local.cwd doesn't work if cwd changes by non-plumbum means

---

README.rst

Basically tell RST compiler that it's Python/bash. Github specifically makes no assumptions hence no highlighting without these.

Syntax highlighting in README

---

plumbum/machines/session.py

This is a better error message than `EOFError`, hopefully will make #111, #173, and maybe #187 a little clearer by reminding users that bash must be on the remote machine as the default shell. This also makes trying to connect to a non-existent server give a better error message - and the error message is different for this case, making it possible to tell if the remote is accessible at all.

Better error message

---

.gitignore
docs/local_commands.rst
plumbum/__init__.py
plumbum/commands/__init__.py
plumbum/commands/base.py
plumbum/commands/daemons.py
plumbum/commands/modifiers.py
plumbum/machines/base.py
plumbum/machines/local.py
plumbum/machines/remote.py
plumbum/machines/ssh_machine.py
plumbum/path/base.py
plumbum/path/local.py
plumbum/path/remote.py
tests/slow_process.bash
tests/test_local.py
tests/test_nohup.py
tests/test_remote.py

This patch adds two things:
1:
I've added a NOHUP modifier, working on both local and ssh_machines. It unifies the syntax for the two machines and makes it easier to use. The classic methods of doing this, `local.daemonic_popen` and `ssh_machine.nohup` are still supported for compatibility. As part of the patch, minor cleanup was done on execution modifiers class structure. The nohup modifier is a little like bash syntax:
```python
>>> local['sleep'][1.234] & NOHUP
```
vs.
```bash
>>> nohup sleep 1.234 & 
```
It defaults to nohup's std output, but can use new output files and `"/dev/null"` too, and can append or replace. It even respects `>` and `>>` on the command it is applied to.
Like bash's nohup, it disconnects from the process started, even if the current process/shell is exited.
2: …

Nohup and glob

---

docs/cli.rst
plumbum/cli/__init__.py
plumbum/cli/application.py
plumbum/cli/switches.py
plumbum/colorlib/styles.py
plumbum/lib.py
tests/test_cli.py
tests/test_validate.py

​Adding positional arguments decorator to `plumbum.cli`. This allows positional or named validators to be added via a decorator on the main function. Default arguments do not go through the validator. For example:
```python
class MyApp(cli.Application):
@cli.positional(int, float, cli.ExistingFile)
def main(self, myint, myfloat, *inputs):
assert isinstance(myint,int)
...
```
This also supports Python 3 notation:
```python
class MyApp(cli.Application):
def main(self, myint : int, myfloat : float, *inputs : cli.ExistingFile):
assert isinstance(x,int)
...
```
Also fixed a bug with missing `__slots__` in `ABC`, causing `ABC` subclasses to be `__dict__` classes.
Besides convenience and clarity, especially for variable args, this is going to be important for 1.7.0 if we can get argument …

Positional argument decorator

---

plumbum/machines/remote.py
plumbum/path/base.py
plumbum/path/local.py
plumbum/path/remote.py
tests/test_local.py
tests/test_remote.py

This patch changes path to be a subclass of str, similar to unipath. Since path was always supposed to be immutable, this was a simple change. The only api change is that cwd behaves slightly differently; due to the latest changes with the way it's now generated when you call local.cwd, this should be completely transparent. (For example, all tests pass). You now can use the as clause of a with statement to grab the new path.
Because of this change, treating the path like a string now works as expected; you can use `.endswith`, etc., and you can even directly open a path without converting it to a string first.

Path subclassing str

---

examples/geet.py
plumbum/cli/application.py

This small patch allows customization or removal of the extra help message on subcommands, addresses #232. You can remove a subcommand extra help message by setting the class variable `SUBCOMMAND_HELPMSG` to `False`/`None`, or you can customize it with a string (`{parent}` and `{sub}` refer to the parent and subcommand name, respectively, in the string).
Also fixed color output on subcommands, the help message color matches the subcommand color now, if the subcommand color was set. See the geet.py example for an example of both changes.
PS: Unrelated to this patch: Travis fails occasionally, simple rerunning of the failed matrix element without changes fixes the problem.

Fix for extra help message

---

plumbum/commands/base.py
plumbum/commands/processes.py
plumbum/machines/base.py
plumbum/machines/local.py
plumbum/machines/paramiko_machine.py
plumbum/machines/session.py
tests/test_local.py

Fixes #241 by making the (new) verify method on command objects responsible for determining whether to raise an exception.

Ensure fair error attribution of pipelined return codes

---

docs/cli.rst
examples/simple_cli.py
plumbum/cli/application.py

This adds calling an `Application()` directly without arguments as a shortcut to `Application.run()`. This is needed for some systems with entry points (like conda) that do not support a `.` in the entry point syntax.

Cli direct run

---

plumbum/machines/remote.py
plumbum/path/remote.py

This is a proposed fix for #236, absolute paths now shortcut to being used without calling pwd directly.
This also uses `._cwd` to stash the current working directory. If the attribute exists, that is used instead of the cwd. I think this is the only allowed way to change the path; if `('cd', ...)` is called directly through the machine it will not change the stash here. This is similar to the old behavior in < 1.6.0, but still keeping the immutable nature of the 1.6.0 paths.

Remote cwd overuse

---

plumbum/commands/modifiers.py
tests/test_validate.py

This pipes run_proc's timeout argument farther up the stack.
I'm hoping the tests will catch if this hits any parts that don't accept timeout and I'll add it to those as well.

Add timeouts into the ExecutionModifiers

---

plumbum/machines/paramiko_machine.py

`set_combine_stderr` takes an argument since at least 2004.

Fix combining stderr in paramiko_machine

---

plumbum/commands/base.py

Hi!
I've noticed, that current implementation does not allow to disable returncode verification for the whole pipeline (Pipeline tree),
eg. `(netstat["-tnlp"] | grep[pid] | grep[port])(retcode = None)` fails at grep[pid]: nonzero returncode
while `(netstat["-tnlp"] | grep[pid])(retcode = None)` works as expected
Am I missing something?
Thanks! :)

Apply retcode=None to the whole Pipeline tree (ie. when >2 commands in pipeline)

---

plumbum/commands/base.py

Refactoring `__getitem__` into a normal method that `__getitem__` calls. Due to the odd tuple behavior of `__getitem__`, it is harder to use as an explicit method call than the other special methods. Was added in response to #296.
Should not affect any existing code, as it just adds an alternate way to call a command using method syntax.

`__getitem__` seperation

---

plumbum/cli/application.py

Previous behavior looks like this
```
Error: Argument of output expected to be <plumbum.cli.switches.Predicate object at 0x10ce91c10>, not 'requirements.txt':
ValueError('output is a file, should be a directory',)
```
now looks like this
```
Error: Argument of output expected to be 'MakeDirectory', not 'requirements.txt':
ValueError('output is a file, should be a directory',)
```
when checking a `Predicate`.

Make argument type error messages use `__str__` method of `Predicate`s

---

plumbum/cli/application.py

With a switch defined like this,
```
checkpoint_fname = cli.SwitchAttr('--checkpoint', argtype=local.path, default='/tmp/lm2d_to_pose.hd5')
```
on master, the output looks like this,
```
--checkpoint VALUE:<bound method LocalMachine.path of <plumbum.machines.local.LocalMachine object at 0x10c9b1710>>
```
This PR makes it look like this,
```
--checkpoint VALUE:path             Sets an attribute
```

Help on switches use the function's name

---

CHANGELOG.rst
plumbum/machines/remote.py
tests/test_local.py
tests/test_remote.py

This fixes globbing a remote filesystem with spaces, fixes #322. These had to be manually escaped, since the for loop in bash uses space as a separator.

Escape filename spaces on remotes, fixes #322

---

CHANGELOG.rst
CONTRIBUTING.rst
plumbum/commands/base.py
plumbum/lib.py
tests/test_local.py

Python 2 Plumbum fails (for example, on Travis) if you have unicode in your output. This fixes that, and tests it.
It is still not supported to use a unicode path in Python 2 (and probably that limitation will remain until Python 2 dies).

Unicode fixes for Python 2 (and tests for Python 3)

---

conda.recipe/meta.yaml
dev-requirements.txt
plumbum/commands/base.py
plumbum/machines/local.py
tests/test_local.py

This enables the use-case where a Python function takes a file object as
argument. For instance (with boto3):
with cmd.bgrun(stdin=PIPE) as f:
boto3.download_fileobj(bucket, key, f.proc.stdin)
The first PR (#355) broke functionality because it changed the behavior of Popen objects. Specifically, the dstproc Popen object had a non-None stdin field that it didn't understand how to deal with. This change avoids that problem by not exposing a stdin to the underlying Popen object. The only way I could think to do this was by switching from inheritance (in IterablePopen) to composition.

Make it possible to write to stdin of a pipeline (try #2)

---

plumbum/cli/image.py
tests/test_color.py

This fixes #365. I can't actually find when this syntax became illegal, but this replacement works both in Python 2.7 and 3.6 whereas the original doesn't.
As I wrote in #365, this patch unbreaks installs under versions of `pip` that have a hard dependency on the `py->pyc` step succeeding.

image.py: fix old-style(?) relative import statement

---

.travis.yml
dev-requirements.txt
plumbum/machines/ssh_machine.py
tests/test_putty.py

This is a fix for issue #369. If a PuttyMachine instance is created to an ssh server that is running on the non-default port, then the upload and download methods fail, because `pscp` is still using the default port instead of the actual port.
I have added some tests. The tests verify:
- PuttyMachine calls the `__init__` of SshMachine with the correct parameters
- PuttyMachine includes the correct port option for pscp with non-default ports
- `PuttyMachine.__str__` has the expected message.
The tests can run on any system even without Putty installed. One of the test fails on PyPy, but it is marked with `@xfail_on_pypy`. It fails on PyPy because the feature of `pytest-mock` used in that test does not work on PyPy.

Support PuttyMachine file upload and download using non-default port

---

build.py
plumbum/cli/application.py
plumbum/cli/i18n.py
tests/test_cli.py

The accelerated translations if the language is English (for #364 in 1.6.5) broke one of the error messages #371. This fixes #371.

Fix quick translation bug

---

.ci/travis.sh
.travis.yml

Now `brew install python` installs python3.
Should fix the travis builds so PRs will start succeeding again.

Fixing after Python brew change on macOS

---

Pipfile

This should fix Python 2.6 build failures.
Python 2.6 is still supported by Plumbum for now since it is the default Python on Scientific Linux 6 and CentOS/RHEL 6. (Technically, RHEL 5 is still supported, and that's Python 2.4, but enough is enough). 
This ought to fix the only  problem with #386, too.

Adding marker to ensure Paramiko is not installed on Python 2.6

---

CHANGELOG.rst
plumbum/colorlib/styles.py
plumbum/commands/processes.py

This fixes errors when exiting pytest in other projects in some rare cases.

Atexit support improved

---

plumbum/path/base.py

Not critical, since Plumbum's path inherit from str. Found in #396.

Fix name of fspath

---

docs/cli.rst
plumbum/cli/application.py
tests/test_cli.py

One feature I missed from argparse is the ability to have abbreviations or partial switches (such as "--foo" matching "--foobar", assuming no ambiguous conflicts). This patch attempts to add that. I also added a unit test and it seems to pass. I'm not sure if the authors are in favor of this feature, but sharing it in case it would be beneficial to others.
P.S. I looked around in the code and docs for an already existing implementation, I hope I didn't miss it and do redundant work :-)

allow switch abbrevations as an option

---

plumbum/path/base.py
tests/test_remote.py

``RemotePath.parents`` and dependent properties such as ``RemotePath.parent`` don't work (cf. tests added in first commit and [their results in CI](https://travis-ci.org/smheidrich/plumbum/builds/426517903)) because [the method that is used](https://github.com/tomerfiliba/plumbum/blob/22db2e82b114c02592716530241448bb66b76fdf/plumbum/path/base.py#L404-L410) (actually from ``base.Path``) uses a single argument for ``__class__`` to construct the new path objects, while [``RemotePath`` needs at least two ](https://github.com/tomerfiliba/plumbum/blob/22db2e82b114c02592716530241448bb66b76fdf/plumbum/path/remote.py#L37) (the first one being the remote machine, not present in ``base.Path``).
The 2nd commit aims to fix this by using the ``_form`` method instead of ``__class__`` to construct new …

Fix RemotePath.parents (and thereby e.g. RemotePath.parent)

---

plumbum/path/remote.py
tests/test_remote.py

While ``LocalPath.open`` [is implemented](https://github.com/tomerfiliba/plumbum/blob/22db2e82b114c02592716530241448bb66b76fdf/plumbum/path/local.py#L223-L225) and works fine, ``RemotePath.open`` is currently an [empty placeholder method](https://github.com/tomerfiliba/plumbum/blob/22db2e82b114c02592716530241448bb66b76fdf/plumbum/path/remote.py#L296-L297). However, for ``ParamikoMachine``-associated paths, an implementation is trivial due to the existence of [``SFTPClient.file``](http://docs.paramiko.org/en/latest/api/sftp.html#paramiko.sftp_client.SFTPClient.file), which does pretty much exactly what we want.
This PR exploits that fact and offers a simple implementation of ``RemotePath.open`` which uses ``SFTPClient.file`` for ``ParamikoMachine``-associated paths<sup>1</sup> and raises …

Implement RemotePath.open for ParamikoMachine-associated paths

---

dev-requirements.txt
plumbum/commands/daemons.py
tests/test_nohup.py

posix_daemonize failed to close a file handle, which lead to resource exhaustion if you NOHUP'd many thousands of subprocesses.
This commit adds a test demonstrating the leak and closes the appropriate file.

Fix file handle leak in NOHUP / posix_daemonize

---

plumbum/machines/remote.py
plumbum/path/base.py
plumbum/path/local.py
plumbum/path/remote.py
tests/test_local.py
tests/test_remote.py

This PR aims to make the ``mkdir`` method of Plumbum's path classes (local & remote) more compatible with [``pathlib.Path.mkdir``](https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir) by implementing the arguments ``parents`` and ``exist_ok`` that are present in the latter. The ``mode`` argument has also been added to the argument list to match the signature of pathlib's method and preserve backwards-compatibility once it is implemented in the future, but I haven't implemented it yet, because pathlib does some umask-voodoo that I'd have to look into in more detail. I might add it later.
Should be backwards-compatible with earlier Plumbum ``mkdir`` behavior (which unfortunately required choosing defaults different from pathlib's, however) and of course comes with tests.

Towards pathlib.Path.mkdir compatibility

---

docs/local_commands.rst

Mention Python 3 behavior, explain in more detail what is going on, and fix typo.
Fixes #412.

Docs: update remark on required parentheses

---

plumbum/path/base.py
plumbum/path/local.py
tests/test_local.py
tests/test_remote.py

As a continuation of #410, this PR implements the "mode" argument for ``LocalPath.mkdir``, which turned out to be trivial, as the umask stuff that is mentioned in ``pathlib.Path.mkdir``'s docs also applies to ordinary ``os.mkdir`` (it actually goes back to the ``mkdir`` syscall).
It's still not implemented for ``RemotePath.mkdir``, because the ``mkdir`` shell command (used by Plumbum's remote mkdir implementation) handles the ``--mode`` argument differently, namely without the umask transformation done by the ``mkdir`` syscall, so it's a bit more involved. We'd have to retrieve the umask of the remote process manually in order to do that transformation, but I'm not sure whether one should then also be able to set the remote umask and how that should work in detail. So I'll look into it …

Implement mode argument for LocalPath.mkdir

---

dev-requirements.txt

Should clear the way for #434 .

Fixing travis error for Python 2.6

---

plumbum/commands/modifiers.py
tests/test_local.py

Even if the child process has exited, it may have written data that is
still in the pipe buffer. We need to make sure to drain it with one
final round of `select()`ing.
Note that this differs from the shell semantics of `| tee file.out`;
In a shell pipeline, the right-hand-side has no direct reference to
the left-hand-side, and so `tee` reads until it gets an `EOF` on the
pipe, normally caused by all write-side ends being closed. We can
demonstrate this with a pipeline that causes the write end to outlive
the left-hand child:
```
( sleep 500 & disown; echo hi ) | tee out.log
```
After the `hi` is printed, we can observe that the left-hand `bash` is
dead, but `tee` still has not returned:
```
$ pstree -p 7273
bash(7273)───tee(1790)
```
Killing the `sleep` makes the whole pipeline exit.
I …

Fix bug #395.

---

.ci/travis.sh
.travis.yml
dev-requirements.txt
plumbum/cli/switches.py
setup.py
tests/test_remote.py

If no help msg is provided to switchattr, but a default is, give it a help msg that's the default msg with the leading '; ' stripped; fixes #433

Show default value msg as help msg when default value is supplied without explicit help msg

---

plumbum/machines/base.py
tests/test_local.py
tests/test_remote.py

Provide a more elegant syntax for running commands:
`machine.cmd.ls("-la")`

machine.cmd

---

tests/test_remote.py

Hoping to fix macOS test failure.

Make sure skip is passed a string

---

plumbum/path/base.py
plumbum/path/local.py

Fixes #245. Please comment on whether this is a good plan, or provide suggestions.
Same behavior as current Plumbum if no arguments supplied.

Better documented behavoir for override, drop overwrite

---

plumbum/cli/switches.py
tests/test_cli.py

Fix for bug mentioned in https://github.com/tomerfiliba/plumbum/pull/452#issuecomment-532635333

Fix cli set validator

---

README.rst

Fixes #463. Does this look like a good idea to everyone?

Small touchup for readme

---

plumbum/machines/local.py
tests/test_local.py

This fixes a regression introduced in 108342ad9f7580bd0ada0cf100ddf7620bf73f9e.
It appears that this commit tried to implement a transparent proxy object for `subprocess.Popen`. Unfortunately, special method calls  (e.g. of context manager methods by the `with` statement) generally circumvent the `__getattribute__` machinery and perform direct lookup.
This leads to an exception when calling LocalCommand.popen() within a with statement:
``` python
>>> from plumbum import local
>>> ls = local['ls']
>>> with ls.popen():
...     print("yay")
... 
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
AttributeError: __enter__
```
This broke some code of mine. I have not found any documentation regarding this change, so I assume dropping the context manager functionality was an …

Fix context manager for LocalCommand.popen()

---

plumbum/commands/processes.py

This feature never worked on win32, since it doesn't support using `select` with anything but sockets...
The only way I found to implement it was to use two threads

fix support for win32 in iter_lines

---

plumbum/path/base.py
tests/test_local.py

Plumbum doesn't support PathLike logics, because Path class is inherited from str and therefore considered as str in python libraries (`__fspath__ `method is never called). Before #455 everything was fine, but after the corresponding commit libraries are unable to use plumbum Path as string, because `__getitem__` returns strange thinks for int and slice keys.
Consider the following example:
```
import os
import plumbum
print(os.path.splitext(plumbum.local.path('/test/file.ext')))
```
Before #455 the output is as expected:
>('/test/file', '.ext')
But after the commit it is meaningless:
> (<LocalPath /test/file.ext/slice(None, 10, None)>, <LocalPath /test/file.ext/slice(10, None, None)>)
I fix this bug by returning the old `__getitem__` behaviour for `int` and `slice` keys.

Fix incorrect __getitem__ method in Path

---

plumbum/machines/session.py

(Not sure if there's some philosophy against dealing with concurrency in plumbum?...)

make ShellSession thread-safe when using .run()

---

plumbum/commands/processes.py
plumbum/machines/session.py

We fail so frequently on various ssh configuration problems, and yet the error messages are mostly uninformative:
```
01:59:07 | No stderr result detected. Does the remote have Bash as the default shell?
...
01:59:07 |   */plumbum/machines/session.py:277 ................................ run >> return run_proc(self.popen(cmd), retcode)
01:59:07 |   */plumbum/commands/processes.py:292 ......................... run_proc >> stdout, stderr = proc.communicate()
01:59:07 |   */plumbum/machines/session.py:136 ........................ communicate >> msgerr) if name == "2" else SSHCommsError(msg)
```
It seems that the code was not ready for various other return codes

ssh: better error reporting on SshSession errors

---

plumbum/path/local.py
tests/test_local.py

So basically there was a bug in `LocalPath.__fspath__`: we tried to call `self._path()` where `_path` is a property.
I solved the problem by just inheriting the implementation from Path, as `Path.__fspath__` is implemented correctly:
```
def __fspath__(self):                                                                                                                          
"""Added for Python 3.6 support"""                                                                                                         
return str(self)    
```

Fix TypeError:  'str' object is not callable in LocalPath.__fspath__

---

plumbum/path/remote.py

call RemotePath.delete (a method) instead of RemotePath.remove (not a method)

fixes RemotePath.copy()

---

docs/_cheatsheet.rst
docs/local_machine.rst
plumbum/commands/base.py
plumbum/machines/local.py
plumbum/machines/paramiko_machine.py
plumbum/machines/ssh_machine.py
setup.cfg
tests/test_local.py
tests/test_remote.py

Fix handling of env-vars passed to plumbum BoundEnvCommands:
- don't use the non-threadsafe and session-dependent .env() context manager
- sync popen support for 'env' param in all machine impls: local/ssh/paramiko
- add .with_cwd() to complement .with_env()

fix handling of env-vars passed to plumbum Commands; support new with_cwd

---

setup.py

chore: drop codecs from setup.py

---

tests/test_local.py

GitHub moved to Ubuntu 20.04 as `ubuntu-latest`, which breaks a tests that assumes `ls` is in `/bin`. This fixes that assumption.

tests: ubuntu-20.04 has /usr/bin/ls, breaks a test

---

docs/conf.py

The documentation config file seems to identify the project license as CC-BY-SA 3.0; fixing it to say MIT instead, as that is the actual license.

Fixing project license in docs config file

---

setup.cfg

I don't think we use this anymore. CC https://github.com/readthedocs/recommonmark/issues/221

docs: remove recommonmark

---

docs/cli.rst
docs/quickref.rst
examples/SimpleColorCLI.py
examples/geet.py
plumbum/cli/application.py
tests/test_clicolor.py

Hello,
Thanks a lot for the great framework!
I'm migrating a CLI app from `click` to `plumbum` and it's going like a charm!
But got an idea for a small feature/improvement;
hence the pull request:
- `COLOR_GROUP_TITLES` property introduced and documented
- `test_clicolor.py` modified to cover the new case
Cheers,
Peter

Introducing new Application property: COLOR_GROUP_TITLES

---

CHANGELOG.rst
plumbum/machines/ssh_machine.py
tests/test_remote.py

I tried to make the interface as sane as possible while maintaining as a small diff and backwards compatibility. Let me know if you'd like it to look different. Thanks for working on this project!
OpenSSH clients can forward Unix sockets instead of TCP ports with the
same `-L` flag using a slightly modified argument. This patch should
allow users to take advantage of the full syntax. From the man pages:
```
-L [bind_address:]port:host:hostport
-L [bind_address:]port:remote_socket
-L local_socket:host:hostport
-L local_socket:remote_socket
```
This patch also adds a protection for the feature.

Add support for OpenSSH forwarding Unix sockets

---

plumbum/commands/processes.py

Setting the python property is supported python 2.6+

setDaemon is deprecated in python 3.10

---

plumbum/machines/ssh_machine.py
tests/test_remote.py

SSH supports the creation of reverse tunnels using a very similar syntax to normal tunnels. From the man pages:
```
-R [bind_address:]port:host:hostport
-R [bind_address:]port:local_socket
-R remote_socket:host:hostport
-R remote_socket:local_socket
-R [bind_address:]port
```
This PR adds a flag to the `.tunnel()` method of `SshMachine` that allows for easy creation of a reversed SSH tunnel

Add convenience flag for reverse ssh tunnels

---

noxfile.py
plumbum/lib.py
plumbum/path/local.py
tests/conftest.py
tests/test_local.py

Addresses only the local part of https://github.com/tomerfiliba/plumbum/issues/481 with minimal changes and no new dependencies. I haven't worked with the remote parts of plumbum, sorry.

fix: glob characters in local paths

---

setup.cfg

`pypiwin32` is an unmaintained redirect to `pywin32`
This PR changes the requires to point directly at the `pywin32` package
It also means that pywin32 will correctly have the `platform_system=='Windows'` markers, which is important for projects using Pipenv

Directly reference pywin32 in requirements 

---

plumbum/machines/ssh_machine.py
plumbum/path/base.py

After the next release, let's bump these up to the final level of warning. 2.0 will remove these old aliases.

chore: intensify warning for eventual removals

---

plumbum/machines/remote.py

Try to use `mktemp -d` before falling back to calling mktemp with an explicit template (for compat. with some BSD variants of mktemp (see #176)).
Testing shows shows that this fixes temp dirs being created in the current working directory on systems using a recent current GNU coreutils mktemp variant and on systems using the mktemp variant packaged with some macOS versions (e.g. 10.15). This may also fix the issue on other systems as well (see https://stackoverflow.com/a/2792789).
(Oddly, this fixes the issue on macOS 10.15, but not on macOS 11.6, which does not have the issue in the first place despite mktemp having an identical man page on 10.15 and 11.6.)

Try to avoid creating temp dirs in the current working directory

---

.pre-commit-config.yaml
CHANGELOG.rst
plumbum/cli/i18n.py
plumbum/fs/atomic.py
setup.cfg

This is expected to be the final (save for possible patch release) 2.7 & 3.5 compatible release.
- chore: bump pre-commit
- docs: update changelog
- chore: drop unneeded line

chore: prepare for 1.7.2

---

plumbum/cli/i18n.py
plumbum/cli/termsize.py
plumbum/colorlib/names.py

Started adding types (using monkeytype), and hit a possible bug that was probably hidden by a too-broad except.

fix: add types and fix issue with ioctrl + Python 3

---

plumbum/__init__.py
plumbum/cmd.py

Only fall back to the old implementation on Python 3.6.

refactor: use Python 3.7 simpler impl for cmd

---

plumbum/commands/processes.py
tests/test_local.py

Something in recent refactors broke this capability, which we are using in our infrastructure, so I've fixed and cemented it with a UT.

exceptions: ensure ProcessExecutionError can be pickled

---

plumbum/commands/base.py
tests/test_local.py

_I.e._ fixed:
(cat << "meow") & FG
Modifiers writing to stdout – _e.g._: `FG`, `TEE`, `RETCODE(FG=True)` and
`TF(FG=True)` – invoke commands with the specification `stdin=None`.
This is handled correctly by `BaseCommand`; however, `StdinDataRedirection`
misinterprets this as a further attempt to specify stdin (_i.e._ to
specify _something_ rather than _nothing_).
This change brings `StdinDataRedirection` in line with its base class,
ignoring `None` as well as `PIPE`.
(Though a technical detail, the class would also have failed any
invocation setting `stdin=PIPE`, along the lines of: "TypeError: got
multiple values for keyword argument 'stdin'". The kwargs passed to the
wrapped command's `popen` are corrected as well.)
resolves #604

made StdinDataRedirection compatible with modifiers writing to stdout

---

plumbum/machines/session.py
plumbum/machines/ssh_machine.py
tests/test_remote.py

Hi! This adds two new features:
*   Reverse (Open)SSH tunnels with dynamically allocated remote ports. E.g.
```python
> tun = SshMachine(...).tunnel(1234, 0, reverse=True)
> tun.dport
'43385'
```
Dynamic remote port allocation is done by OpenSSH (`ssh -R`).
*   Non-reverse and reverse (Open)SSH tunnels with dynamically allocated local ports. E.g.
```python
> tun = SshMachine(...).tunnel(0, 1234)
> tun.lport
37689
```
Dynamic local port allocation is done by `rpyc.utils.factory._get_free_port`, which I've duplicated into Plumbum. (Minor point: license-wise, `rpyc.utils.factory._get_free_port` is released by @tomerfiliba under the MIT license already. In theory Plumbum should add attribution to satisfy RPyC's license here, but I suspect that Tomer probably would not mind as they authored …

Support SSH tunnels with dynamic free port allocation

---

docs/cli.rst
plumbum/cli/switches.py
pyproject.toml
tests/test_cli.py

Closes #547. Has fewer changes, does some code modernization, and is always opt-in, which gives better backward compatibility.

feat: add all_markers to Set

---

.github/workflows/ci.yml
.pre-commit-config.yaml
plumbum/cli/application.py
pyproject.toml
tests/test_3_cli.py

Closes #599. Globals/locals logic is likely better in 3.10+.

fix: support future annotations

---

.github/workflows/ci.yml
.gitignore
plumbum/machines/local.py
setup.cfg
tests/test_local.py

This will allow users to use the API as follows:
```python
from plumbum import local
from pathlib import Path
local[Path('/path/to/binary')]()
```

local: accept path-like (`pathlib.Path`) objects

---

plumbum/path/base.py

We are currently integrating pyright checks in our project. We found that generally pyright is great at inferring the return types by just looking at the source code of libraries. However for abstractmethods which only contain a docstring it assumes that the method is supposed to return None since there's no return statement.
This minimal set of hints seems to help pyright figure out how plumbum paths work.

Add type hints to abstractmethods of Path

---

docs/local_commands.rst

I have been struggling with https://github.com/tomerfiliba/plumbum/pull/632, but until the issue is fixed, a warning in documentation sounds like a good idea. Happy to reword it any way you like :)
https://github.com/tomerfiliba/plumbum/issues/548

Add warning about pipeline stalling to documentation

---

.github/workflows/cd.yml
.github/workflows/ci.yml

ci: use trusted publisher deployment

---

.pre-commit-config.yaml
pyproject.toml

See https://github.com/scientific-python/cookie/pull/200.

chore: ruff moved to astral-sh

---

plumbum/commands/base.py
plumbum/commands/processes.py
tests/test_pipelines.py

When a command (other than the first) in a pipeline wrote more than 64k to the stderr, and the output was consumed with the iter_lines function, the whole pipeline stalled. Fixed by reading the output of all commands where either stdout or stderr was set to PIPE.
This is the same issue as described in
https://github.com/tomerfiliba/plumbum/issues/548
Same problem still exists if command is executed with run(), but that code calls proc.communicate to read stderr/stdout and I do not know how to fix that.

Fix stalling in Pipeline command

---

plumbum/commands/modifiers.py
tests/test_local.py

I checked that modified test is failing, and fix in this branch makes it green.
Fixes #660

Fix missing non-zero return code from TEE'd pipe

---

plumbum/commands/base.py

The StdinDataRedirection command object was returning a list inside a list, which caused trouble when getting the "str()" of the command.
Simple example to demonstrate the problem:
Python 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from plumbum.cmd import head
>>> cmd = head['-2'] << "one\ntwo\nthree\nfour"
>>> print(f"{cmd}")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Python310\lib\site-packages\plumbum\commands\base.py", line 66, in __str__
return " ".join(self.formulate())
TypeError: sequence item 2: expected str instance, list found
>>>
This addresses open issue #398

Fix StdinDataRedirection's formulate() method

---

.pre-commit-config.yaml
plumbum/cli/image.py
plumbum/cli/switches.py
plumbum/typed_env.py
pyproject.toml

Switching to Ruff's built-in black-like formatter. See https://github.com/scientific-python/cookie/pull/299.

chore: switch to ruff-format

---

.github/workflows/ci.yml
.pre-commit-config.yaml
experiments/parallel.py
plumbum/cli/application.py
plumbum/cli/terminal.py
plumbum/cli/termsize.py
plumbum/colorlib/__main__.py
plumbum/colorlib/factories.py
plumbum/colorlib/names.py
plumbum/colorlib/styles.py
plumbum/colors.py
plumbum/commands/processes.py
pyproject.toml
tests/test_remote.py

chore: bump pre-commit

---

plumbum/cli/i18n.py

Another part of #678, the "C" locale (no locale set) should also take the fast path.

fix: use high-speed method for C locale too

---

.github/workflows/cd.yml
.github/workflows/ci.yml
plumbum/colorlib/styles.py
plumbum/commands/base.py
pyproject.toml

Getting the classifier for the upcoming 3.13 release.

ci: add 3.13

---

.github/workflows/ci.yml
plumbum/cli/i18n.py
tests/test_translate.py

Simple test of translated CLI code.

fix: setuptools-less installs couldn't translate, add test

---

.pre-commit-config.yaml
plumbum/cli/i18n.py
pyproject.toml

See about fixing one of the two issues in #678 by getting off pkg_resources. I think this won't work as I wrote it on Python < 3.12, as that is when directories were added, but let's see.
TODO: add a test, it shouldn't have worked, directories weren't supported until 3.12.

fix: use importlib resources

---

.github/workflows/ci.yml

Currently, the install 3.13 jobs are slow. See if this helps.

ci: try to make faster with more uv

---

plumbum/machines/paramiko_machine.py
tests/test_remote.py

While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [paramiko_machine.py](https://github.com/tomerfiliba/plumbum/blob/master/plumbum/machines/paramiko_machine.py#L190), class: `RemoteCommand`, there is a special method `__or__` that raises a NotImplementedError. If a special method supporting a binary operation is not implemented it should return NotImplemented. On the other hand, NotImplementedError should be raised from abstract methods inside user defined base classes to indicate that derived classes should override those methods. iCR suggested that the special method `__or__ `should return NotImplemented instead of raising an exception. An example of how NotImplemented helps the interpreter support a binary operation is …

Fixed Improper Method Call: Replaced `NotImplementedError`

---

pyproject.toml

Hatchling `v1.27.0` added support for [PEP 639](https://peps.python.org/pep-0639/) license expressions.
Metadata diff
```diff
...
-License: Copyright (c) 2013 Tomer Filiba (tomerfiliba@gmail.com)
-        
-        Permission is hereby granted, free of charge, to any person obtaining a copy
-        of this software and associated documentation files (the "Software"), to deal
-        in the Software without restriction, including without limitation the rights
-        to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-        copies of the Software, and to permit persons to whom the Software is
-        furnished to do so, subject to the following conditions:
-        
-        The above copyright notice and this permission notice shall be included in
-        all …
```

chore: use SPDX license identifier
